plugins {
    id "application"
}

def atomicEditVersion = "0.4.0"

def lwjglVersion = "3.3.6"
def imguiVersion = "1.89.0"

repositories {
    mavenCentral()
    jcenter()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    implementation "org.lwjgl:lwjgl"
    implementation 'org.lwjgl:lwjgl-glfw'
    implementation 'org.lwjgl:lwjgl-opengl'
    
    ["natives-windows", "natives-linux", "natives-macos", "natives-macos-arm64"].each { lwjglNatives ->
        implementation "org.lwjgl:lwjgl:${lwjglVersion}:${lwjglNatives}"
        implementation "org.lwjgl:lwjgl-glfw:${lwjglVersion}:${lwjglNatives}"
        implementation "org.lwjgl:lwjgl-opengl:${lwjglVersion}:${lwjglNatives}"
        //compile "org.lwjgl:lwjgl-tinyfd:${lwjglVersion}:${lwjglNatives}"
    }
    
    //imgui for UI   https://github.com/SpaiR/imgui-java
    implementation "io.github.spair:imgui-java-binding:$imguiVersion"
    implementation "io.github.spair:imgui-java-lwjgl3:$imguiVersion"
    ["imgui-java-natives-windows", "imgui-java-natives-linux", "imgui-java-natives-macos"].each { imguiNatives ->
        implementation "io.github.spair:${imguiNatives}:$imguiVersion"
    }
    
    //gson for some json parsing. TODO remove this
    implementation 'com.google.code.gson:gson:2.13.1'
    
    //vector math
    implementation "org.joml:joml:1.10.5"

    //tests
    testImplementation 'junit:junit:4.12'
}

application {
    mainClass = "Main"
}

tasks.named('test') {
    useJUnitPlatform() 
}

/*
jar {
    //destinationDirectory = buildDir
    baseName = "AtomicEdit_" + "$atomicEditVersion"
    manifest{
        attributes "Main-Class": "Main"
    }
    from {
        configurations.compile.collect {
            it.isDirectory() ? it : zipTree(it) 
        }
    }
}
*/

processResources {
    def replace = { replaceMap ->
        return { line ->
            def newLine = line
            replaceMap.each { matchRegex, replaceStr ->
                if (line =~ matchRegex) {
                    newLine =  replaceStr
                }
            }
            return newLine
        }
    }
    filesMatching('version.txt', { file ->
        file.filter(replace([
            "atomicedit_version" : atomicEditVersion
        ]))
    })
}
